### PR TITLE
added a small timer.sleep to allow the DOWN message to be processed

### PR DESCRIPTION
**Pull request by tomjoro**
I saw your irc chat and checked the code and had same problem.I think the documentation is misleading and probably should be updated?

### CODE REVIEW

**Comment by vseehausen** [comment]
Amazing. Thanks a lot.

But still I want to receive this message! :) I Will ask again in irc.

**Comment by Valentin-Seehausen** [comment]
Thanks a lot!

(Still I want to know, if I can receive this message.)

**Comment by tomjoro** [comment]
The message is processed.. I added a IO.puts to verify that the DOWN message is received - the problem is you don't know _when_ it is received and in this case it is after the test. So I think the only way to fix it would be to somehow send another message after down is done?

**Comment by tomjoro** [comment]
BTW.. I asked in irc and fishcakez_ commented that it's not technically possible. But I think the documentation is misleading and should be fixed (I followed everything through like you did ).

**Comment by tomjoro** [comment]
" In the repo there is a docs/ folder, where the docs live in it. ??" Where is that?

**Comment by vseehausen** [comment]
It is here: https://github.com/elixir-lang/elixir-lang.github.com/blob/master/getting-started/mix-otp/supervisor-and-application.markdown . Love github :)

-> By the way, I went on and realized that our "bug" is topic in the next chapter, ETS. Did you see it, too?

**Pull request merged**
